name: "Test"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        kongVersion:
        # - "2.7.x"
        - "2.8.x"
        # - "2.8.1.x"
        - "3.0.x"

    steps:
    - uses: actions/checkout@v3
    - uses: Kong/kong-pongo-action@v1
      with:
        kong_version: ${{ matrix.kongVersion }}
        # non-Kong-Inc users should uncomment the following line and provide
        # the secret by that name if testing against Enterprise versions.
        # Kong Inc users should use the `Kong/kong-license` action
        license: ${{ secrets.KONG_LICENSE_DATA }}
    - run: pongo run -- --coverage
